language: python
python:
  - "3.6"
env:
  - DJANGO_VERSION=2.0.7
install:
  - pip install -r requirements.txt
script:
  - python manage.py test quotes
  - python manage.py runserver & python manage.py test