language: python
addons: # get google-chrome-stable
  chrome: stable
install: # Install ChromeDriver (64bits; replace 64 with 32 for 32bits).
  - wget -N http://chromedriver.storage.googleapis.com/2.40/chromedriver_linux64.zip -P ~/
  - unzip ~/chromedriver_linux64.zip -d ~/
  - rm ~/chromedriver_linux64.zip
  - sudo mv -f ~/chromedriver /usr/local/bin/
  - sudo chmod a+x /usr/local/bin/chromedriver
  - sudo ln -s /usr/local/bin/chromedriver /usr/local/bin/chromedriver
python:
  - "3.6"
env:
  - DJANGO_VERSION=2.0.7
install:
  - pip install -r requirements.txt
script:
  - python manage.py test quotes
  - PATH=$PATH:/usr/local/bin/chromedriver ; whereis chromedriver
  - whereis chromedriver
  # - PATH=$PATH:/usr/local/share/chromedriver ; python manage.py runserver & python manage.py test