sudo: false
language: python
addons: # get google-chrome-stable
  # chrome: stable
  apt:
    packages:
      - google-chrome-stable
      - chromium-chromedriver
before_script:
  - ln -s /usr/lib/chromium-browser/chromedriver ~/bin/chromedriver
install: # Install ChromeDriver (64bits; replace 64 with 32 for 32bits).
  - wget http://chromedriver.storage.googleapis.com/2.40/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d /home/travis/virtualenv/python3.6/bin/
  - export CHROME_BIN=chromium-browser
python:
  - "3.6"
env:
  - DJANGO_VERSION=2.0.7
install:
  - pip install -r requirements.txt
script:
  - python manage.py test quotes
  - python manage.py runserver & python manage.py test functional_tests
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master