sudo: required
language: python
addons: # get google-chrome-stable
  chrome: stable
install: # Install ChromeDriver (64bits; replace 64 with 32 for 32bits).
  - wget http://chromedriver.storage.googleapis.com/2.40/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d /home/travis/virtualenv/python3.6/bin/
  - export CHROME_BIN=chromium-browser
python:
  - "3.6"
env:
  - DJANGO_VERSION=2.0.7
install:
  - pip install -r requirements.txt
script:
  - python manage.py test quotes
  - PATH=$PATH:/usr/local/bin/chromedriver ; whereis chromedriver
  - whereis chromedriver
  # - PATH=$PATH:/usr/local/share/chromedriver ; python manage.py runserver & python manage.py test